# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=256, verbose_name='Content Name')),
                ('is_draft', models.BooleanField(verbose_name='Draft')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('content_value', models.TextField(verbose_name='Content Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=256, verbose_name='Content Name')),
                ('is_draft', models.BooleanField(verbose_name='Draft')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('content_value', models.TextField(verbose_name='Content Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=256, verbose_name='Content Name')),
                ('is_draft', models.BooleanField(verbose_name='Draft')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('content_value', models.CharField(max_length=256, verbose_name='Content Value')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
